import "@/utils/zod-config"
import { useEffect, useState } from "react"
import { browser } from "#imports"
import { Button } from "@/components/ui/base-ui/button"
import { renderPersistentReactRoot } from "@/utils/react-root"
import "@/assets/styles/theme.css"

interface PageExportPayload {
  title: string
  url: string
  mainContent: string
  selectedText: string
  exportedAt: string
}

function PageExportApp() {
  const [page, setPage] = useState<PageExportPayload | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let printTimer: ReturnType<typeof setTimeout> | undefined

    void (async () => {
      const exportId = location.hash.slice(1)
      if (!exportId) {
        setError("Missing export payload.")
        return
      }
      const key = `owlnest-page-export:${exportId}`
      const stored = await browser.storage.local.get(key)
      const payload = stored[key] as PageExportPayload | undefined
      if (!payload) {
        setError("Export payload expired. Please export again from OwlNest.")
        return
      }
      setPage(payload)
      await browser.storage.local.remove(key)
      printTimer = setTimeout(() => window.print(), 350)
    })()

    return () => {
      if (printTimer)
        clearTimeout(printTimer)
    }
  }, [])

  if (error) {
    return (
      <main className="mx-auto max-w-2xl px-8 py-10">
        <h1 className="text-2xl font-semibold">OwlNest Page Export</h1>
        <p className="mt-4 text-sm text-destructive">{error}</p>
      </main>
    )
  }

  if (!page) {
    return <main className="p-8 text-sm text-muted-foreground">Loading export...</main>
  }

  return (
    <main className="mx-auto max-w-3xl px-8 py-10 text-foreground print:max-w-none print:px-0 print:py-0">
      <div className="mb-6 flex justify-end print:hidden">
        <Button onClick={() => window.print()}>Save as PDF</Button>
      </div>
      <article className="space-y-6">
        <header className="space-y-2 border-b pb-5">
          <div className="text-sm font-medium text-muted-foreground">Generated by OwlNest Agent</div>
          <h1 className="text-3xl font-semibold leading-tight">{page.title}</h1>
          <p className="break-all text-sm text-muted-foreground">
            Source:
            {page.url}
          </p>
          <p className="text-sm text-muted-foreground">
            Exported at:
            {page.exportedAt}
          </p>
        </header>

        {page.selectedText && (
          <section className="space-y-2">
            <h2 className="text-xl font-semibold">Selected Text</h2>
            <p className="whitespace-pre-wrap text-sm leading-7">{page.selectedText}</p>
          </section>
        )}

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">页面内容</h2>
          <p className="whitespace-pre-wrap text-sm leading-7">{page.mainContent}</p>
        </section>
      </article>
    </main>
  )
}

const root = document.getElementById("root")!
root.className = "min-h-screen bg-background text-base antialiased"

renderPersistentReactRoot(root, <PageExportApp />)
